const $=selector=>document.querySelector(selector),$$=selector=>[...document.querySelectorAll(selector)];
const titles={general:'General',visual:'Visual',misc:'Misc',settings:'Settings'};
const defaults={theme:'noir',ui:'classic',version:'2.5',compact:false,motion:true,scale:100,sidebarCollapsed:false,activeTab:'general',ranges:{amount:68,intensity:42,opacity:85},toggles:[true,false,true,false,true,true,false,true],checks:[true,false,true],keys:['INSERT','NONE'],selects:['Default','First']};
const uiNames={classic:'Classic',stellar:'Stellar',horizon:'Horizon',dock:'Dock'};
let state=load(),toastTimer,listening=null;
function load(){try{const saved=JSON.parse(localStorage.getItem('fractual.ui')||'{}');if(!['noir','graphite2','paper','contrast'].includes(saved.theme))saved.theme='noir';return{...defaults,...saved,ranges:{...defaults.ranges,...saved.ranges}}}catch{return structuredClone(defaults)}}
function save(){localStorage.setItem('fractual.ui',JSON.stringify(state))}
function icons(){window.lucide?.createIcons({icons:window.lucide.icons,attrs:{'stroke-width':1.7}})}
function toast(message){$('#toast span').textContent=message;$('#toast').classList.remove('show');void $('#toast').offsetWidth;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),1500)}
function motionSwap(change){if(document.startViewTransition&&state.motion&&document.body.classList.contains('booting'))return document.startViewTransition(change);change()}
function tab(name,persist=true){if(!titles[name])return;const current=$('.page.active')?.dataset.page;const change=()=>{$$('.nav').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));$$('.page').forEach(p=>p.classList.toggle('active',p.dataset.page===name));$('#page-title').textContent=titles[name];state.activeTab=name;if(persist)save();icons()};current===name?change():motionSwap(change)}
function setRange(input,value){input.value=value;input.style.setProperty('--value',`${(value-input.min)/(input.max-input.min)*100}%`);const output=$(`#${input.id}-value`);if(output)output.textContent=input.id==='scale'?`${value}%`:value;if(input.id==='opacity')$('.preview-box').style.opacity=value/100;if(input.id==='scale')document.documentElement.style.setProperty('--ui-scale',value/100)}
function apply(){document.body.dataset.theme=state.theme==='graphite'?'':state.theme;document.body.classList.toggle('compact',state.compact);document.body.classList.toggle('reduced-motion',!state.motion);document.body.classList.toggle('sidebar-collapsed',state.sidebarCollapsed);$$('.theme').forEach(b=>b.classList.toggle('active',b.dataset.theme===state.theme));$('#compact-toggle').classList.toggle('on',state.compact);$('#motion-toggle').classList.toggle('on',state.motion);$('#sidebar-toggle').setAttribute('aria-expanded',String(!state.sidebarCollapsed));$('#sidebar-toggle').title=`${state.sidebarCollapsed?'Expand':'Collapse'} sidebar (Ctrl+B)`;['amount','intensity','opacity'].forEach(id=>setRange($('#'+id),state.ranges[id]));setRange($('#scale'),state.scale);$$('.toggle:not(#compact-toggle):not(#motion-toggle)').forEach((b,i)=>b.classList.toggle('on',!!state.toggles[i]));$$('.checkbox').forEach((b,i)=>b.classList.toggle('on',!!state.checks[i]));$$('.keybind').forEach((b,i)=>b.querySelector('kbd').textContent=state.keys[i]||'NONE');$$('select').forEach((s,i)=>s.value=state.selects[i]||s.options[0].value);tab(state.activeTab,false)}

$$('.nav').forEach(button=>button.onclick=()=>tab(button.dataset.tab));
$('#sidebar-toggle').onclick=()=>{if(window.innerWidth<=720){document.body.classList.toggle('sidebar-mobile-open');toast(document.body.classList.contains('sidebar-mobile-open')?'Sidebar opened':'Sidebar closed')}else{state.sidebarCollapsed=!state.sidebarCollapsed;save();apply();toast(state.sidebarCollapsed?'Sidebar collapsed':'Sidebar expanded')}};
$$('[data-subtab]').forEach(button=>button.onclick=()=>motionSwap(()=>{$$('[data-subtab]').forEach(b=>b.classList.toggle('active',b===button));$$('[data-subpage]').forEach(p=>p.classList.toggle('active',p.dataset.subpage===button.dataset.subtab))}));
$$('.toggle').forEach(button=>button.onclick=()=>{button.classList.toggle('on');button.animate?.([{transform:'scale(.95)'},{transform:'scale(1.025)'},{transform:'scale(1)'}],{duration:220,easing:'cubic-bezier(.22,1,.36,1)'});if(button=== $('#compact-toggle'))state.compact=button.classList.contains('on');else if(button===$('#motion-toggle'))state.motion=button.classList.contains('on');else state.toggles=$$('.toggle:not(#compact-toggle):not(#motion-toggle)').map(b=>b.classList.contains('on'));save();apply();toast(button.classList.contains('on')?'Enabled':'Disabled')});
$$('.checkbox').forEach(button=>button.onclick=()=>{button.classList.toggle('on');state.checks=$$('.checkbox').map(b=>b.classList.contains('on'));save()});
[['amount','amount-value'],['intensity','intensity-value'],['opacity','opacity-value'],['scale','scale-value']].forEach(([id])=>$('#'+id).oninput=event=>{const value=Number(event.target.value);setRange(event.target,value);if(id==='scale')state.scale=value;else state.ranges[id]=value;save()});
$$('select').forEach((select,index)=>select.onchange=()=>{state.selects[index]=select.value;save();toast('Selection saved')});
$$('.theme').forEach(button=>button.onclick=()=>{state.theme=button.dataset.theme;save();apply();document.querySelector('.window').animate?.([{opacity:.88},{opacity:1}],{duration:320,easing:'cubic-bezier(.22,1,.36,1)'});toast(`${button.textContent.trim()} applied`)});
$$('.keybind').forEach((button,index)=>button.onclick=()=>{if(listening)return;listening={button,index};button.classList.add('listening');button.querySelector('kbd').textContent='...';toast('Press any key')});
document.addEventListener('keydown',event=>{if(listening){event.preventDefault();const value=event.key==='Escape'?'NONE':event.key.toUpperCase();listening.button.querySelector('kbd').textContent=value;listening.button.classList.remove('listening');state.keys[listening.index]=value;listening=null;save();toast(value==='NONE'?'Keybind cleared':'Key saved');return}if(event.ctrlKey&&event.key.toLowerCase()==='b'){event.preventDefault();$('#sidebar-toggle').click()}if(event.ctrlKey&&['1','2','3','4'].includes(event.key)){event.preventDefault();tab(['general','visual','misc','settings'][Number(event.key)-1])}},{capture:true});
$('#color-swatch').onclick=event=>{event.currentTarget.classList.toggle('alternate');toast('Accent preview changed')};
$('#action-button').onclick=event=>{event.currentTarget.textContent='Complete';event.currentTarget.animate?.([{transform:'scale(.98)'},{transform:'scale(1)'}],{duration:220});setTimeout(()=>event.currentTarget.textContent='Run action',850);toast('Action complete')};
$('#reset-button').onclick=()=>{state=structuredClone(defaults);save();apply();applyUI();syncVersion();toast('Interface reset')};
function applyUI(){const ui=uiNames[state.ui]?state.ui:'classic';document.body.dataset.ui=ui;$('#ui-swap-current').textContent=`${uiNames[ui]} frame`}
function syncVersion(){const select=$('#version-select');const version=['2.5','2.4','2.2','2.1','2.0','1.9','1.8','1.7','1.5','1.4','1.3','1.0'].includes(state.version)?state.version:'2.5';state.version=version;select.value=version;$('#app-version').textContent=`v${version}`;$('#brand-version').textContent=`UI / ${version}`;document.body.dataset.version=version}
$('#version-select').onchange=event=>{state.version=event.target.value;save();syncVersion();document.querySelector('.content').animate?.([{opacity:.76,transform:'translateY(.15rem)'},{opacity:1,transform:'none'}],{duration:340,easing:'cubic-bezier(.22,1,.36,1)'});toast(`Version ${state.version} selected`)};
const uiOrder=['classic','stellar','horizon','dock'];let stageIndex=0;
function renderStage(direction=0){const cards=$$('.cover-card'),length=cards.length;cards.forEach((card,index)=>{let offset=(index-stageIndex+length)%length;if(offset>length/2)offset-=length;card.dataset.position=String(offset);card.classList.toggle('active',offset===0);card.setAttribute('aria-selected',String(offset===0))});$$('.stage-dots i').forEach((dot,index)=>dot.classList.toggle('active',index===stageIndex));const title=$('#stage-title');title.textContent=uiNames[uiOrder[stageIndex]];title.animate?.([{opacity:0,transform:`translateX(${direction*12}px)`},{opacity:1,transform:'none'}],{duration:260,easing:'cubic-bezier(.2,.8,.2,1)'})}
function moveStage(amount){stageIndex=(stageIndex+amount+uiOrder.length)%uiOrder.length;renderStage(amount)}
function swapOpen(open){$('#ui-stage').classList.toggle('open',open);$('#ui-stage').setAttribute('aria-hidden',String(!open));document.body.classList.toggle('selector-open',open);if(open){stageIndex=Math.max(0,uiOrder.indexOf(state.ui));renderStage();$('#stage-close').focus()}}
function chooseStage(){state.ui=uiOrder[stageIndex];save();applyUI();$('.shell').animate?.([{opacity:.72,transform:'scale(.99)'},{opacity:1,transform:'scale(1)'}],{duration:420,easing:'cubic-bezier(.22,1,.36,1)'});swapOpen(false);toast(`${uiNames[state.ui]} UI applied`)}
$('#ui-swap-trigger').onclick=()=>swapOpen(true);$('#stage-close').onclick=()=>swapOpen(false);$('#stage-prev').onclick=()=>moveStage(-1);$('#stage-next').onclick=()=>moveStage(1);$('#stage-apply').onclick=chooseStage;
$$('.cover-card').forEach((card,index)=>card.onclick=()=>{if(index===stageIndex)chooseStage();else{const forward=(index-stageIndex+uiOrder.length)%uiOrder.length;stageIndex=index;renderStage(forward<=2?1:-1)}});
$('#window-min').onclick=()=>window.desktop?.minimize();$('#window-max').onclick=()=>window.desktop?.maximize();$('#window-close').onclick=()=>window.desktop?.close();
document.addEventListener('keydown',event=>{if(!$('#ui-stage').classList.contains('open'))return;if(event.key==='Escape')swapOpen(false);if(event.key==='ArrowLeft')moveStage(-1);if(event.key==='ArrowRight')moveStage(1);if(event.key==='Enter')chooseStage()});
function finishBoot(){const boot=$('#boot-screen');boot.classList.add('complete');setTimeout(()=>boot.setAttribute('aria-hidden','true'),500)}
function installRails(){$$('.panel').forEach(panel=>{if(panel.querySelector('.fractual-rail'))return;const rail=document.createElement('span');rail.className='fractual-rail';rail.innerHTML='<i></i><i></i><i></i><i></i>';panel.appendChild(rail);panel.querySelectorAll('.row,.keybind,.check-row,.theme,.wide-button').forEach(target=>target.addEventListener('pointerenter',()=>{const box=panel.getBoundingClientRect(),item=target.getBoundingClientRect();panel.style.setProperty('--rail-y',`${item.top-box.top+item.height/2}px`);panel.classList.add('rail-active')}));panel.addEventListener('pointerleave',()=>panel.classList.remove('rail-active'))})}
document.addEventListener('click',event=>{if(!event.target.closest('.toggle,.checkbox,.wide-button,.nav,.theme,.cover-card,#stage-prev,#stage-next,#stage-apply'))return;const brand=$('.brand');brand.classList.remove('brand-pulse');void brand.offsetWidth;brand.classList.add('brand-pulse');setTimeout(()=>brand.classList.remove('brand-pulse'),520)});
window.addEventListener('resize',()=>{if(window.innerWidth>720)document.body.classList.remove('sidebar-mobile-open')});
const updateAction=$('#update-action'),updateStatusText=$('#update-status'),updateChip=$('#update-chip');let updaterState='idle';
function showUpdate(status={}){updaterState=status.state||'idle';const labels={idle:'AUTO',checking:'CHECKING',available:'FOUND',downloading:`${Math.round(status.percent||0)}%`,downloaded:'RESTART',current:'CURRENT',error:'RETRY',disabled:'INSTALLER'};updateStatusText.textContent=status.message||'Updates check automatically';updateChip.textContent=labels[updaterState]||'AUTO';updateAction.className=`row update-row ${updaterState}`;updateAction.style.setProperty('--update-progress',`${Math.max(0,Math.min(100,status.percent||0))}%`)}
async function setupUpdates(){if(!window.desktop?.updates){showUpdate({state:'disabled',message:'Install Fractual Setup once to enable automatic updates'});return}window.desktop.updates.onStatus(showUpdate);showUpdate(await window.desktop.updates.getStatus())}
updateAction.onclick=async()=>{if(updaterState==='downloaded'){window.desktop?.updates?.install();return}if(updaterState==='disabled'){toast('Use Fractual Setup once, then updates are automatic');return}showUpdate({state:'checking',message:'Checking for updates…'});try{await window.desktop?.updates?.check()}catch{showUpdate({state:'error',message:'Update check failed — click to retry'})}};
apply();applyUI();syncVersion();icons();installRails();setupUpdates();(window.requestAnimationFrame||setTimeout)(()=>document.body.classList.add('booting'));setTimeout(finishBoot,1250);
